apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-07
labels:
  appName: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
    appName: nginx
  template:
    metadata:
      labels:
        appName: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/rkalluru/nginx:hostname-print
